# mkdocs.yml
site_name: RCD

extra_files:
  - CNAME

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: "material"
  features:
    - navigation.tabs
    - content.code.select
    - content.code.copy

plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: sphinx
  - section-index

nav:
  - Home: index.md
  - Code references:
      - reference.md
      - RSL Base: code-reference/rsl-base.md
      - RSL-D: code-reference/rsl-d.md
      - RSL-W: code-reference/rsl-w.md
      - MARVEL: code-reference/marvel.md
      - L-MARVEL: code-reference/l-marvel.md
      - ROL-HC: code-reference/rol-hc.md